id = "arduino"
name = "Arduino Language Support"
version = "0.0.2"
schema_version = 1
authors = ["Derock Xie <derock@derock.dev>", "Talana <s.j.kusters@proton.me>"]
description = "Complete Arduino development with auto-setup, IntelliSense, board auto-detection, 23 tasks, and 141 snippets."
repository = "https://github.com/SB-CMR-Talana/zed-arduino"
snippets = ["languages/arduino/snippets.json"]

[language_servers.arduino-language-server]
name = "Arduino Language Server"
languages = ["Arduino"]

[grammars.arduino]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-arduino"
commit = "017696bdf47ca2b10948c5a511f9ab387722d0f3"
